definitions:
  handler.TStructure:
    properties:
      access_token:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  handler.Todo:
    properties:
      completed:
        type: boolean
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: This is an API for Todo Application
  title: Todo App
  version: "1.0"
paths:
  /api/add/todo:
    post:
      consumes:
      - application/json
      description: Create todo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Todo'
      summary: Create todo
      tags:
      - todo
  /api/auth:
    post:
      consumes:
      - application/json
      description: Auth
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TStructure'
      summary: Auth
      tags:
      - auth
  /api/todos:
    get:
      consumes:
      - application/json
      description: Get all todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Todo'
            type: array
      summary: Get all todos
      tags:
      - todo
  /api/todos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete todo
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete todo
      tags:
      - todo
    get:
      consumes:
      - application/json
      description: Get once todo
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Todo'
      summary: Get once todo
      tags:
      - todo
    patch:
      consumes:
      - application/json
      description: Edit todo
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Todo'
      summary: Edit todo
      tags:
      - todo
swagger: "2.0"
